### ISSUE TITLE
Add 3D Robotics

### ISSUE THREAD

**Issue by kasbah** [waldyrious/awesome-open-company#10]
[3D Robotics](http://3drobotics.com) have open source products and also steward [Arducopter](http://www.arducopter.co.uk/) I believe.

**Comment by waldyrious** [comment]
3D Robotics isn't such a clear-cut case, I'm afraid. The commitment to openness, if any, isn't at all explicit on their website. For instance, the [about page](http://3drobotics.com/about/) has at best this line: 

> Under Chris’s stewardship, 3DR’s global neurosystem of volunteers soon created a world-class universal flight code, called APM. In collaboration with the renowned Swiss research institute ETH Zurich, **3DR used this code to develop the Pixhawk, to this day the world’s leading open autopilot platform.**

No mention is made regarding what "open" means in this context.

The [community page](http://3drobotics.com/community/) is somewhat better. It seems to indicate that the company originated from an "open robotics community", DIYDrones, but doesn't make it clear that this openness was preserved in the company. There's a paragraph that sounds initially promising:

> Makers everywhere can now create their own apps for the platform (and for Solo) through **DroneKit—3DR’s open application development platform for drones—**and even take them to market for free via 3DR Services.

...but then goes on to say:

> The platform code itself is now stewarded by the international Dronecode Foundation, which welcomes and facilitates contributions of individuals and companies around the world.

...making it sound like the openness is preserved by the Dronecode Foundation rather than 3D Robotics.

Furthermore, the [Terms page](http://3drobotics.com/terms/) isn't very reassuring regarding this topic, particularly the "Copyright" section:

> The entire content included in this site, including but not limited to text, graphics or code is copyrighted (...), and is the property of 3D Robotics Inc. (...) Permission is granted to electronically copy and print hard copy portions of this site **for the sole purpose of placing an order with 3D Robotics Inc or purchasing 3D Robotics Inc products**. You may display and (...) download or print portions of the material from the different areas of the site **solely for your own non-commercial use, or to place an order with 3D Robotics Inc or to purchase 3D Robotics Inc products**. **Any other use, including but not limited to the reproduction, distribution, display or transmission of the content of this site is strictly prohibited**, unless authorized by 3D Robotics Inc.

Granted, that's just related to the website's contents, not the actual products, but still doesn't help their case.

All in all, I wouldn't say this is a good candidate to add to this list as an open company, unless their commitment to openness is made more explicit. I'm open to be convinced otherwise, of course.

**Comment by kasbah** [comment]
Fair enough, I am not invested on way or the other, just a suggestion since you do link to Chris Anderson's talk and he owns part of this company and uses it as an example. I do find his equality of open source to free labour a bit annoying.

**Comment by waldyrious** [comment]
I see. I suppose I'm not comfortable with extrapolating from such implicit evidence. If you have no objections, I'll close this issue for now, without discarding the option to reopen should their commitment to openness be made more explicit. Thanks for the suggestion nevertheless!
